default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_46929_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_46929_test
  prepared_statements: false
  pool: 25
  checkout_timeout: 30
  variables:
    transaction_isolation: "READ-COMMITTED"

production:
  <<: *default
  adapter: mysql2
  database: furima_46929_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock